services:
  eureka-service:
    image: eureka-service:0.0.1-SNAPSHOT
    ports:
      - "8761:8761"

  cambio-db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cambio_db

  cambio-service:
    image: cambio-service:0.0.1-SNAPSHOT
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://cambio-db:5432/cambio_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-service:8761/eureka
    depends_on:
      - cambio-db
      - eureka-service
    deploy:
      replicas: 2      



  produto-db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: produto_db

  produto-service:
    image: produto-service:0.0.1-SNAPSHOT
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://produto-db:5432/produto_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-service:8761/eureka
    depends_on:
      - produto-db
      - eureka-service
      - cambio-service

  api-gateway-service:
    build:
      context: ./api.gateway-service  # Caminho para o diretório do Dockerfile
    image: api-gateway-service:0.0.1-SNAPSHOT  # Nome da imagem
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-service:8761/eureka
    ports:
      - "8765:8765"  # Altere a porta se necessário
    depends_on:
      - eureka-service
      - cambio-service
